### ISSUE TITLE
Need help with the run function

### ISSUE THREAD

**Issue by LBH20** [WSWUP/AeroEvap#1]
Hello,
I am new to python and am attempting to use the python code to calculate evaporation. I have followed everything in the AeroEvap read the docs. I am currently using a small section of the sample data used in the tutorial to test if the code is working properly. So far all the functions work, except from the run function. The single calculation function works exactly as described in the tutorial.

The run function keeps going on an endless loop, and gives a "Runtime Error," as seen in the picture provided. If anyone knows why this is occurring please let me know. 

I am using Windows 10, Visual Studio Code,  Python 3.8 64 bit.

Thanks. 
![error code](https://user-images.githubusercontent.com/62489354/77239828-2a7b1100-6b9c-11ea-8e8a-439f288f553c.png)

**Comment by JohnVolk** [comment]
Thank you for posting this, after doing some searching I think it may have to do with on Windows the module itself is getting imported recursively. It looks like there is an easy way around this according to this [stack exchange post.](https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing) I will try to reproduce on Windows and make the appropriate changes and hopefully this clears it up.

**Comment by JohnVolk** [comment]
So I was able to replicate the issue and fix it using the method suggested the stack exchange post I linked above. It appears to only be related to Windows and Python's multiprocessing module. The fix is straightforward and only involves changing how you call the script. You simply need to place the call to the multiprocessing portion of the code after `if __name__ == '__main__':  ` in this case in ``AeroEvap`` the `Aero.run()` method is the only method that utilizes multiprocessing. By putting this call after  `if __name__ == '__main__':  `  this avoids the Windows interpreter from importing and creating sub-processes from the module recursively. 

Below is a full script that accomplishes the same example in the tutorial, it runs on Windows 10 with Python 3.8. Save it as a ".py" and call it from an interpreter or the command line and it should work for you.


```python
#!/usr/bin/env python
# coding: utf-8

import pandas as pd
import numpy as np
from aeroevap import Aero
import matplotlib.pyplot as plt
np.seterr('ignore')

if __name__ == '__main__':    
    
    names = {
        'WSPD' : 'WS',
        'ATMP' : 'T_air',
        'WTMP' : 'T_skin',
        'PRES' : 'P'
    }

    # get standard meterological data from National Data Buoy Center
    met_df = pd.read_csv(
        'https://www.ndbc.noaa.gov/data/l_stdmet/41008.txt', 
        delim_whitespace=True, skiprows=[1], na_values=[999.0]
    )

    met_df.index = pd.to_datetime(
        dict(
            year=met_df['#YY'], 
            month=met_df.MM, 
            day=met_df.DD, 
            hour=met_df.hh,
            minute=met_df.mm
        )
    )
    met_df.index.name = 'date'
    met_df.drop(['#YY','MM','DD','hh','mm'], axis=1, inplace=True)
    met_df.head()

    # vapor pressure and saturation vapor pressure using Clausius–Clapeyron relation
    met_df['e'] = 0.611 * np.exp( 5423 * ((1/273) - (1/(met_df.DEWP+273.15))) )
    met_df['es'] = 0.611 * np.exp( 5423 * ((1/273) - (1/(met_df.ATMP+273.15))) )

    # calculate relative humitidy
    met_df['RH'] = 100 * (met_df.e/met_df.es)

    A= Aero(met_df)
    A.run(sensor_height=4, timestep=600, variable_names=names,nproc=4)
    print(A.df[['E', 'Ce', 'VPD']].head())

    plt.figure(figsize=(8,4))
    A.df.E.plot()
    plt.ylabel('evaporation mm/10 min')
    plt.show()
```

**Comment by LBH20** [comment]
Thank you for the quick reply. I followed what the stack exchange post said and the code is now working. Attached is the adjusted code that worked for me.
![Fixed Error Message](https://user-images.githubusercontent.com/62489354/77242949-4ba22880-6bc1-11ea-890c-086603f1440c.png)
Just for someone's future reference, the single calculation function should not be included within an if__name__ block to function properly.
